import Head from 'next/head'
import Header from '../components/Header'
import { Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="p-5">
        <span className="text-2xl font-light">Salut Lucas,</span>
        <h1 className="text-3xl mt-2">Road to The Rock le Boss</h1>
      </div>

      {/* Training */}
      <div className="mb-5 ml-5">
        <h2 className="text-2xl">Les Entrainements</h2>
      </div>
      <div>
        <Swiper
          slidesPerView={3}
          spaceBetween={10}
          centeredSlides={true}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          className="mySwiper w-[100%]"
        >
          <SwiperSlide>
            <img className="" src="pectoraux.png" alt="" />
          </SwiperSlide>
          <SwiperSlide>
            <img className="" src="abdos.jpg" alt="" />
          </SwiperSlide>
          <SwiperSlide>
            <img className="" src="bras.png" alt="" />
          </SwiperSlide>
          <SwiperSlide>
            <img className="" src="jambes.jpg" alt="" />
          </SwiperSlide>
        </Swiper>
      </div>

    </div>
  )
}
