import Head from 'next/head'
import Header from '../components/Header'
import { BsFillArrowRightCircleFill } from "react-icons/bs";
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="p-5">
        <span className="text-2xl font-light">Salut Lucas,</span>
        <h1 className="text-3xl mt-2">Road to The Rock le Boss</h1>
      </div>

      {/* Training */}
      <Link href="/sport">
        <div className="relative h-[120px] w-[90%] bg-blue-400 mx-auto rounded-lg pt-3 pl-4">
          <h2 className="text-xl text-white">Les Entrainements</h2>
          <span className="text-white font-light">Pectoraux - Abdominaux - Bras - Dos...</span>

          <div className="absolute bottom-3 right-3">
            <BsFillArrowRightCircleFill fontSize={30} color="white" />
          </div>
        </div>
      </Link>


    </div>
  )
}
